name: Anthony Edward "Tony" Stark
species: Human
placeOfOrigin: Earth
Abilities:
  - Genius-level intellect
  - Highly proficient scientist, engineer, and businessperson
  - Expert hand-to-hand combat
